name: release-finatra

# Publishes twitter/finatra.
#
# Expects a repository dispatch event: https://developer.github.com/v3/repos/#create-a-repository-dispatch-event
# in the form of JSON data POST to /repos/twitter/dodo/dispatches:
# {
#   "event_type": "release_finatra",
#   "client_payload": {
#     "phab_id": "D12345",
#     "version": "17.12.0",
#     "dry_run": true
#   }
# }
env:
  JAVA_OPTS: "-Dsbt.log.noformat=true"
  PGP_KEY: ${{ secrets.PGP_KEY }}
  PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
  PGP_SECRET: ${{ secrets.PGP_SECRET }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
  BINTRAY_PASS: ${{ secrets.BINTRAY_PASS }}
  API_USER: ${{ secrets.API_USER }}
  API_KEY: ${{ secrets.API_KEY }}
defaults:
  run:
    shell: bash
on:
  repository_dispatch:
    types: [release_finatra]

jobs:
  release_finatra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.8
      - uses: olafurpg/setup-gpg@v3
      - name: setup/gpg-secret
        run: ${{ github.workspace }}/bin/gpg-init
      - name: setup/sbt
        run: |
          cp -r ${{ github.workspace }}/bin/.sbt ~/.sbt
      # ensure upstreams have merged develop branch into release
      - name: checkout/util
        uses: actions/checkout@v2.3.4
        with:
          repository: twitter/util
          token: ${{ secrets.API_KEY }}
          ref: release
          path: util
      - name: merge/util
        run: |
          ${{ github.workspace }}/bin/merge --phab-id ${{ github.event.client_payload.phab_id }}  --dry-run ${{ github.event.client_payload.dry_run }} --verbose util
        working-directory: ${{ github.workspace }}/util
      - name: checkout/scrooge
        uses: actions/checkout@v2.3.4
        with:
          repository: twitter/scrooge
          token: ${{ secrets.API_KEY }}
          ref: release
          path: scrooge
      - name: merge/scrooge
        run: |
          ${{ github.workspace }}/bin/merge --phab-id ${{ github.event.client_payload.phab_id }}  --dry-run ${{ github.event.client_payload.dry_run }} --verbose scrooge
        working-directory: ${{ github.workspace }}/scrooge
      - name: checkout/finagle
        uses: actions/checkout@v.2.3.4
        with:
          repository: twitter/finagle
          token: ${{ secrets.API_KEY }}
          ref: release
          path: finagle
      - name: merge/finagle
        run: |
          ${{ github.workspace }}/bin/merge --phab-id ${{ github.event.client_payload.phab_id }}  --dry-run ${{ github.event.client_payload.dry_run }} --verbose finagle
        working-directory: ${{ github.workspace }}/finagle
      - name: checkout/twitter-server
        uses: actions/checkout@v.2.3.4
        with:
          repository: twitter/twitter-server
          token: ${{ secrets.API_KEY }}
          ref: release
          path: twitter-server
      - name: merge/twitter-server
        run: |
          ${{ github.workspace }}/bin/merge --phab-id ${{ github.event.client_payload.phab_id }}  --dry-run ${{ github.event.client_payload.dry_run }} --verbose twitter-server
        working-directory: ${{ github.workspace }}/twitter-server
      # run dodo to build finatra dependencies
      - name: dodo/build
        uses: twitter/dodo-build@v2
        with:
          branch: release
          project: finatra
          no-test: true
          publish-m2: true
          verbose: true
          dry-run: ${{ github.event.client_payload.dry_run }}
      # checkout finatra and release
      - name: checkout/finatra
        uses: actions/checkout@v.2.3.4
        with:
          repository: twitter/finatra
          token: ${{ secrets.API_KEY }}
          ref: release
          path: finatra
      - name: release/finatra
        run: |
          ${{ github.workspace }}/bin/publish --phab-id ${{ github.event.client_payload.phab_id }} --version ${{ github.event.client_payload.version }}  --dry-run ${{ github.event.client_payload.dry_run }} --verbose finatra
        working-directory: ${{ github.workspace }}/finatra
