name: merge-release

# Merges the 'develop' branch into release on pushes to 'develop'
defaults:
  run:
    shell: bash
on:
  push:
    branches: [develop]

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.1
        with:
          fetch-depth: 0
          ref: develop
      - name: merge
        run: |
          develop_head=$(git rev-parse HEAD)
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git checkout release && git merge "$develop_head" && git push -f origin release

