name: release-util

# Publishes twitter/util.
#
# Expects a repository dispatch event: https://developer.github.com/v3/repos/#create-a-repository-dispatch-event
# in the form of JSON data POST to /repos/twitter/dodo/dispatches:
# {
#   "event_type": "release_util",
#   "client_payload": {
#     "phab_id": "D12345",
#     "version": "17.12.0",
#     "dry_run": true
#   }
# }
env:
  JAVA_OPTS: "-Dsbt.log.noformat=true"
  PGP_KEY: ${{ secrets.PGP_KEY }}
  PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
  PGP_SECRET: ${{ secrets.PGP_SECRET }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
  BINTRAY_PASS: ${{ secrets.BINTRAY_PASS }}
  API_USER: ${{ secrets.API_USER }}
  API_KEY: ${{ secrets.API_KEY }}
defaults:
  run:
    shell: bash
on:
  repository_dispatch:
    types: [release_util]

jobs:
  release_util:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.8
      - uses: olafurpg/setup-gpg@v3
      - name: setup/gpg-secret
        run: ${{ github.workspace }}/bin/gpg-init
      - name: setup/sbt
        run: |
          cp -r ${{ github.workspace }}/bin/.sbt ~/.sbt
      # checkout util and release
      - name: checkout/util
        uses: actions/checkout@v2.3.4
        with:
          repository: twitter/util
          ref: release
          path: util
      - name: release/util
        run: |
          ${{ github.workspace }}/bin/publish --phab-id ${{ github.event.client_payload.phab_id }} --version ${{ github.event.client_payload.version }}  --dry-run ${{ github.event.client_payload.dry_run }} --verbose util
        working-directory: ${{ github.workspace }}/util
